# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
env:
  APPLICATION_NAME: "Java Courses Tutorials"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Launch build step
      run: echo "Build phase for {{ env.APPLICATION_NAME }} started"
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
  complete:
  
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Complete build process
        run: echo "Completed"
